services:
  - type: web
    name: reeder-radio-backend
    runtime: node
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build && cd .. && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
